[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = true
via_ir = true
remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "account-abstraction/=lib/account-abstraction/contracts/",
]
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
fs_permissions = [
  { access = "read", path = "./metadata" },
  { access = "read-write", path = "./test/fixtures" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Network configurations
[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

# Monad Testnet network profile
[profile.monad_testnet]
chain_id = 10143
rpc_url = "https://testnet-rpc.monad.xyz"
